// Color options for products
export const productColors = {
  white: { name: 'White', hex: '#FFFFFF' },
  black: { name: 'Black', hex: '#000000' },
  red: { name: 'Red', hex: '#EF4444' },
  blue: { name: 'Blue', hex: '#3B82F6' },
  green: { name: 'Green', hex: '#10B981' },
  yellow: { name: 'Yellow', hex: '#F59E0B' },
  pink: { name: 'Pink', hex: '#EC4899' },
  purple: { name: 'Purple', hex: '#A855F7' },
  gray: { name: 'Gray', hex: '#6B7280' },
  navy: { name: 'Navy', hex: '#1E3A8A' },
  cream: { name: 'Cream', hex: '#FEF3C7' },
  mint: { name: 'Mint', hex: '#6EE7B7' },
}

export const products = [
  {
    id: '1',
    name: 'Custom Photo Acrylic Stand',
    description: 'Beautiful transparent acrylic stand perfect for displaying your favorite photos. Customizable with any image.',
    price: 199.99,
    images: ['https://images.unsplash.com/photo-1513519245088-0e12902e35ca?w=800&h=800&fit=crop'],
    category: 'ACRYLIC_STANDS',
    customizable: true,
    stock: 50,
    featured: true,
    themeTags: ['aesthetic', 'valentine'],
  },
  {
    id: '2',
    name: 'Floating Wall Frame',
    description: 'Modern floating acrylic wall frame that adds depth to your artwork. Available in multiple sizes.',
    price: 249.99,
    images: ['https://images.unsplash.com/photo-1582139329536-e7284fece509?w=800&h=800&fit=crop'],
    category: 'WALL_FRAMES',
    customizable: false,
    stock: 30,
    featured: true,
    themeTags: ['aesthetic', 'motivation'],
  },
  {
    id: '3',
    name: 'Cute Fridge Magnet Set',
    description: 'Set of 6 colorful acrylic fridge magnets with custom designs. Perfect for personalizing your kitchen.',
    price: 159.99,
    images: ['https://images.unsplash.com/photo-1611954463558-003de540b93b?w=800&h=800&fit=crop'],
    category: 'FRIDGE_MAGNETS',
    customizable: true,
    stock: 100,
    featured: true,
    themeTags: ['anime', 'valentine'],
  },
  {
    id: '4',
    name: 'LED Acrylic Display Stand',
    description: 'Illuminated acrylic stand with LED base. Create stunning displays with color-changing lights.',
    price: 299.99,
    images: ['https://images.unsplash.com/photo-1590736969955-71cc94901144?w=800&h=800&fit=crop'],
    category: 'ACRYLIC_STANDS',
    customizable: true,
    stock: 25,
    featured: true,
    themeTags: ['anime', 'motivation'],
  },
  {
    id: '5',
    name: 'Premium Gallery Frame',
    description: 'Premium quality acrylic frame for art prints and photographs. Crystal clear with secure mounting.',
    price: 349.99,
    images: ['https://images.unsplash.com/photo-1513519245088-0e12902e35ca?w=800&h=800&fit=crop'],
    category: 'WALL_FRAMES',
    customizable: false,
    stock: 20,
    featured: false,
    themeTags: ['aesthetic', 'motivation', 'valentine'],
  },
  {
    id: '6',
    name: 'Personalized Name Magnet',
    description: 'Custom acrylic magnet with your name or text. Choose from various fonts and colors.',
    price: 179.99,
    images: ['https://images.unsplash.com/photo-1611954463558-003de540b93b?w=800&h=800&fit=crop'],
    category: 'FRIDGE_MAGNETS',
    customizable: true,
    stock: 150,
    featured: false,
    themeTags: ['anime', 'motivation'],
  },
  // Coffee Mugs
  {
    id: '7',
    name: 'Anime Hero Mug',
    description: 'Bold anime-style mug with vibrant hero graphics. Perfect for your morning coffee.',
    price: 189.99,
    images: ['https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?w=800&h=800&fit=crop'],
    category: 'COFFEE_MUGS',
    customizable: false,
    stock: 50,
    featured: true,
    themeTags: ['anime'],
    availableColors: ['white', 'black', 'red'],
    defaultColor: 'white',
  },
  {
    id: '8',
    name: 'Motivation Quote Mug',
    description: 'Start your day right with inspiring quotes. Available in multiple colors.',
    price: 179.99,
    images: ['https://images.unsplash.com/photo-1517256064527-09c73fc73e38?w=800&h=800&fit=crop'],
    category: 'COFFEE_MUGS',
    customizable: false,
    stock: 60,
    featured: true,
    themeTags: ['motivation'],
    availableColors: ['white', 'blue', 'yellow'],
    defaultColor: 'white',
  },
  {
    id: '9',
    name: 'Aesthetic Floral Mug',
    description: 'Elegant mug with minimalist floral design. Perfect for tea or coffee.',
    price: 199.99,
    images: ['https://images.unsplash.com/photo-1534412781266-5dac0d2eb75b?w=800&h=800&fit=crop'],
    category: 'COFFEE_MUGS',
    customizable: false,
    stock: 45,
    featured: true,
    themeTags: ['aesthetic'],
    availableColors: ['white', 'pink', 'cream', 'mint'],
    defaultColor: 'white',
  },
  {
    id: '10',
    name: 'Love Hearts Mug',
    description: 'Romantic mug with hearts design. Perfect gift for Valentine\'s Day.',
    price: 189.99,
    images: ['https://images.unsplash.com/photo-1565345557025-f0f0c6e15d68?w=800&h=800&fit=crop'],
    category: 'COFFEE_MUGS',
    customizable: false,
    stock: 40,
    featured: false,
    themeTags: ['valentine'],
  },
  {
    id: '11',
    name: 'Custom Photo Mug',
    description: 'Create your own mug! Upload any photo and we\'ll print it beautifully.',
    price: 219.99,
    images: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=800&fit=crop'],
    category: 'COFFEE_MUGS',
    customizable: true,
    stock: 100,
    featured: true,
    themeTags: ['all'],
  },
  // Jigsaw Puzzles
  {
    id: '12',
    name: 'Anime Character Puzzle',
    description: '500-piece puzzle featuring your favorite anime characters. Fun challenge!',
    price: 249.99,
    images: ['https://images.unsplash.com/photo-1543286386-2e659306cd6c?w=800&h=800&fit=crop'],
    category: 'JIGSAW_PUZZLES',
    customizable: false,
    stock: 35,
    featured: true,
    themeTags: ['anime'],
  },
  {
    id: '13',
    name: 'Inspirational Landscape Puzzle',
    description: '1000-piece scenic landscape puzzle with motivational message.',
    price: 279.99,
    images: ['https://images.unsplash.com/photo-1553434320-d98a8f992011?w=800&h=800&fit=crop'],
    category: 'JIGSAW_PUZZLES',
    customizable: false,
    stock: 30,
    featured: false,
    themeTags: ['motivation'],
  },
  {
    id: '14',
    name: 'Aesthetic Art Puzzle',
    description: 'Beautiful abstract art puzzle. 750 pieces of pure creativity.',
    price: 269.99,
    images: ['https://images.unsplash.com/photo-1515405295579-ba7b45403062?w=800&h=800&fit=crop'],
    category: 'JIGSAW_PUZZLES',
    customizable: false,
    stock: 25,
    featured: true,
    themeTags: ['aesthetic'],
  },
  {
    id: '15',
    name: 'Custom Photo Puzzle',
    description: 'Turn your favorite photo into a puzzle! Choose from 300, 500, or 1000 pieces.',
    price: 299.99,
    images: ['https://images.unsplash.com/photo-1587731556938-38755b4803a6?w=800&h=800&fit=crop'],
    category: 'JIGSAW_PUZZLES',
    customizable: true,
    stock: 50,
    featured: true,
    themeTags: ['all'],
  },
  // Handkerchiefs
  {
    id: '16',
    name: 'Anime Pattern Handkerchief',
    description: 'Soft cotton handkerchief with colorful anime patterns. Set of 3.',
    price: 169.99,
    images: ['https://images.unsplash.com/photo-1599751449230-3c1b1b0c8b23?w=800&h=800&fit=crop'],
    category: 'HANDKERCHIEFS',
    customizable: false,
    stock: 80,
    featured: false,
    themeTags: ['anime'],
  },
  {
    id: '17',
    name: 'Motivational Quote Handkerchief',
    description: 'Daily reminder handkerchief with uplifting quotes. Premium fabric.',
    price: 189.99,
    images: ['https://images.unsplash.com/photo-1620799140188-3b2a02fd9a77?w=800&h=800&fit=crop'],
    category: 'HANDKERCHIEFS',
    customizable: false,
    stock: 70,
    featured: true,
    themeTags: ['motivation'],
  },
  {
    id: '18',
    name: 'Minimalist Aesthetic Handkerchief',
    description: 'Elegant handkerchief with subtle patterns. Perfect accessory.',
    price: 179.99,
    images: ['https://images.unsplash.com/photo-1578587018452-892bacefd3f2?w=800&h=800&fit=crop'],
    category: 'HANDKERCHIEFS',
    customizable: false,
    stock: 60,
    featured: false,
    themeTags: ['aesthetic'],
  },
  {
    id: '19',
    name: 'Custom Embroidered Handkerchief',
    description: 'Add your initials or custom text. Luxury embroidered handkerchief.',
    price: 199.99,
    images: ['https://images.unsplash.com/photo-1596861219195-ae5b60e08e9a?w=800&h=800&fit=crop'],
    category: 'HANDKERCHIEFS',
    customizable: true,
    stock: 90,
    featured: true,
    themeTags: ['all'],
  },
  // Tote Bags
  {
    id: '20',
    name: 'Anime Style Tote Bag',
    description: 'Spacious tote bag with anime-inspired graphics. Zipper closure for security.',
    price: 229.99,
    images: ['https://images.unsplash.com/photo-1591561954557-26941169b49e?w=800&h=800&fit=crop'],
    category: 'TOTE_BAGS',
    customizable: false,
    stock: 55,
    featured: true,
    themeTags: ['anime'],
    availableColors: ['black', 'navy', 'red'],
    defaultColor: 'black',
  },
  {
    id: '21',
    name: 'Daily Motivation Tote',
    description: 'Carry your motivation everywhere! Durable canvas with inspirational quotes.',
    price: 249.99,
    images: ['https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=800&h=800&fit=crop'],
    category: 'TOTE_BAGS',
    customizable: false,
    stock: 50,
    featured: true,
    themeTags: ['motivation'],
    availableColors: ['white', 'gray', 'blue'],
    defaultColor: 'white',
  },
  {
    id: '22',
    name: 'Aesthetic Minimalist Tote',
    description: 'Chic and stylish tote bag with minimalist design. Perfect for everyday use.',
    price: 239.99,
    images: ['https://images.unsplash.com/photo-1598532163257-ae3c6b2524b6?w=800&h=800&fit=crop'],
    category: 'TOTE_BAGS',
    customizable: false,
    stock: 45,
    featured: false,
    themeTags: ['aesthetic'],
  },
  {
    id: '23',
    name: 'Custom Design Tote Bag',
    description: 'Design your own tote! Upload your artwork or photo for a unique bag.',
    price: 259.99,
    images: ['https://images.unsplash.com/photo-1602458101937-4b5f86b24866?w=800&h=800&fit=crop'],
    category: 'TOTE_BAGS',
    customizable: true,
    stock: 70,
    featured: true,
    themeTags: ['all'],
  },
  // Daily Planners
  {
    id: '24',
    name: 'Anime Life Planner',
    description: 'Organize your life with anime flair! 365 days of colorful planning.',
    price: 279.99,
    images: ['https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?w=800&h=800&fit=crop'],
    category: 'DAILY_PLANNERS',
    customizable: false,
    stock: 40,
    featured: true,
    themeTags: ['anime'],
  },
  {
    id: '25',
    name: 'Goal Crusher Planner',
    description: 'Achieve your dreams! Daily planner with motivational prompts and goal tracking.',
    price: 299.99,
    images: ['https://images.unsplash.com/photo-1531346878377-a5be20888e57?w=800&h=800&fit=crop'],
    category: 'DAILY_PLANNERS',
    customizable: false,
    stock: 35,
    featured: true,
    themeTags: ['motivation'],
  },
  {
    id: '26',
    name: 'Minimalist Aesthetic Planner',
    description: 'Elegant planner with clean layouts. Perfect for the organized minimalist.',
    price: 319.99,
    images: ['https://images.unsplash.com/photo-1517842645767-c639042777db?w=800&h=800&fit=crop'],
    category: 'DAILY_PLANNERS',
    customizable: false,
    stock: 30,
    featured: false,
    themeTags: ['aesthetic'],
  },
  {
    id: '27',
    name: 'Love & Life Planner',
    description: 'Plan your days with love! Romantic design with weekly and monthly spreads.',
    price: 289.99,
    images: ['https://images.unsplash.com/photo-1507925921958-8a62f3d1a50d?w=800&h=800&fit=crop'],
    category: 'DAILY_PLANNERS',
    customizable: false,
    stock: 25,
    featured: false,
    themeTags: ['valentine'],
  },
  {
    id: '28',
    name: 'Personalized Custom Planner',
    description: 'Your planner, your way! Add your name and choose custom cover design.',
    price: 329.99,
    images: ['https://images.unsplash.com/photo-1542831371-29b0f74f9713?w=800&h=800&fit=crop'],
    category: 'DAILY_PLANNERS',
    customizable: true,
    stock: 60,
    featured: true,
    themeTags: ['all'],
  },
]

export const categories = [
  // Old categories
  {
    id: 'acrylic-stands',
    name: 'Acrylic Stands',
    description: 'Custom display stands',
    image: 'https://images.unsplash.com/photo-1513519245088-0e12902e35ca?w=800&h=600&fit=crop',
    slug: 'ACRYLIC_STANDS',
  },
  {
    id: 'wall-frames',
    name: 'Wall Frames',
    description: 'Elegant acrylic frames',
    image: 'https://images.unsplash.com/photo-1582139329536-e7284fece509?w=800&h=600&fit=crop',
    slug: 'WALL_FRAMES',
  },
  {
    id: 'fridge-magnets',
    name: 'Fridge Magnets',
    description: 'Fun custom magnets',
    image: 'https://images.unsplash.com/photo-1611954463558-003de540b93b?w=800&h=600&fit=crop',
    slug: 'FRIDGE_MAGNETS',
  },
  // New categories - Phase 4
  {
    id: 'coffee-mugs',
    name: 'Coffee Mugs',
    description: 'Personalized ceramic mugs',
    image: 'https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?w=800&h=600&fit=crop',
    slug: 'COFFEE_MUGS',
  },
  {
    id: 'jigsaw-puzzles',
    name: 'Jigsaw Puzzles',
    description: 'Custom photo puzzles',
    image: 'https://images.unsplash.com/photo-1543286386-2e659306cd6c?w=800&h=600&fit=crop',
    slug: 'JIGSAW_PUZZLES',
  },
  {
    id: 'handkerchiefs',
    name: 'Handkerchiefs',
    description: 'Designer printed handkerchiefs',
    image: 'https://images.unsplash.com/photo-1599751449230-3c1b1b0c8b23?w=800&h=600&fit=crop',
    slug: 'HANDKERCHIEFS',
  },
  {
    id: 'tote-bags',
    name: 'Zipper Tote Bags',
    description: 'Custom printed tote bags',
    image: 'https://images.unsplash.com/photo-1591561954557-26941169b49e?w=800&h=600&fit=crop',
    slug: 'TOTE_BAGS',
  },
  {
    id: 'daily-planners',
    name: 'Daily Planners',
    description: 'Personalized planners',
    image: 'https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?w=800&h=600&fit=crop',
    slug: 'DAILY_PLANNERS',
  },
]
