import type { Product } from '@/lib/supabase/types'

const now = new Date().toISOString()

export const ladooFallbackProducts: Product[] = [
  {
    id: 'ladoo-1',
    name: 'Dry Fruit Ladoo',
    description: 'बदाम, काजु, खजुर, अंजीर, अक्रोड, पिस्ता, पमकीन सीडीज, सनर्फालवर सीड, जवस',
    price: 200,
    category: 'LADOOS_DRYFRUIT',
    customizable: false,
    stock: 120,
    featured: true,
    default_color: 'standard',
    available_colors: [],
    theme_tags: [],
    images: ['/images/Dry_Fruit.jpg'],
    created_at: now,
    updated_at: now,
  },
  {
    id: 'ladoo-2',
    name: 'Gond Ladoo',
    description: 'खारीक, खोबर, बदाम, काजु, अक्रोड, पिस्ता, गोळबी, डिकं, Jaggery powder',
    price: 300,
    category: 'LADOOS',
    customizable: false,
    stock: 100,
    featured: true,
    default_color: 'standard',
    available_colors: [],
    theme_tags: [],
    images: ['/images/Gond.jpg'],
    created_at: now,
    updated_at: now,
  },
  {
    id: 'ladoo-3',
    name: 'Oats Makhana Ladoo',
    description: 'ओट्स, मखाना, बदाम, काजु, खोबर, अक्रोट, पिस्ता, खडीसाखर',
    price: 250,
    category: 'LIGHT_SWEETS',
    customizable: false,
    stock: 80,
    featured: true,
    default_color: 'standard',
    available_colors: [],
    theme_tags: [],
    images: ['/images/Oats_Makhana.jpg'],
    created_at: now,
    updated_at: now,
  },
  {
    id: 'snack-1',
    name: 'Masala Mixture',
    description: 'Crunchy tea-time namkeen with peanuts, sev, and signature house masala.',
    price: 170,
    category: 'DRY_SNACKS',
    customizable: false,
    stock: 140,
    featured: true,
    default_color: 'standard',
    available_colors: [],
    theme_tags: [],
    images: ['https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=800&h=800&fit=crop'],
    created_at: now,
    updated_at: now,
  },
  {
    id: 'snack-2',
    name: 'Bhujia Classic',
    description: 'Freshly fried crispy bhujia with balanced spice and authentic flavor.',
    price: 150,
    category: 'SNACKS',
    customizable: false,
    stock: 150,
    featured: false,
    default_color: 'standard',
    available_colors: [],
    theme_tags: [],
    images: ['https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=800&h=800&fit=crop'],
    created_at: now,
    updated_at: now,
  },
  {
    id: 'combo-1',
    name: 'Festival Ladoo & Snack Box',
    description: 'Curated gift box with assorted ladoos and savory snacks for celebrations.',
    price: 599,
    category: 'GIFT_BOXES',
    customizable: false,
    stock: 60,
    featured: true,
    default_color: 'standard',
    available_colors: [],
    theme_tags: [],
    images: ['https://images.unsplash.com/photo-1603532648955-039310d9ed75?w=800&h=800&fit=crop'],
    created_at: now,
    updated_at: now,
  },
]
